apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "harvester-node-disk-manager.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harvester-node-disk-manager.labels" . | nindent 4 }}
data:
  {{- if .Values.configMap.filters }}
  filters.yaml: |
    {{- toYaml .Values.configMap.filters | nindent 4 }}
  {{- end }}
  {{- if .Values.configMap.autoprovision }}
  autoprovision.yaml: |
    {{- toYaml .Values.configMap.autoprovision | nindent 4 }}
  {{- end }}
