name: Release Build and Publish

on:
  push:
    tags:
    - v**

jobs:
  build-for-release:
    uses: ./.github/workflows/factory.yaml
    with:
      tag: ${{ github.ref_name }}
      push: true
    secrets: inherit
  create-harvester-pr:
    needs: build-for-release
    uses: ./.github/workflows/create-image-bump-pr.yaml
    with:
      component: harvester-node-disk-manager
      version: ${{ github.ref_name }}
      harvester_repo: harvester/harvester
    secrets: inherit
